apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:eks:us-east-1:555256523315:nodegroup/eks/test-ng/b0b8d349-f935-2ec1-827d-b78c501c001
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - endava:gryphon
      - endava:phoenix
      - endava:behemoth
      - endava:minotaur
      rolearn: arn:aws:iam::555256523315:role/KubernetesDeveloper
      username: k8s-developer-user
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::555256523315:role/eks-node-group-test
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: "- userarn: arn:aws:iam::555256523315:user/Lyubomir.Geshev\n  username:
    Lyubomir.Geshev \n  groups:\n    - system:masters\n- userarn: arn:aws:iam::555256523315:user/Kostadin.Karaivanov\n
    \ username: Kostadin.Karaivanov \n  groups:\n    - system:masters\n- userarn: arn:aws:iam::555256523315:user/jenkins\n  username:
    jenkins \n  groups:\n    - system:masters\n"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- rolearn: arn:aws:eks:us-east-1:555256523315:nodegroup/eks/test-ng/b0b8d349-f935-2ec1-827d-b78c501c0010\n  username: system:node:{{EC2PrivateDNSName}}\n  groups:\n    - system:bootstrappers\n    - system:nodes\n","mapUsers":"- userarn: arn:aws:iam::555256523315:user/Lyubomir.Geshev \n  username: Lyubomir.Geshev \n  groups: \n    - system:masters\n- userarn: arn:aws:iam::555256523315:user/Kostadin.Karaivanov \n  username: Kostadin.Karaivanov \n  groups: \n    - system:masters\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"aws-auth","namespace":"kube-system"}}
  creationTimestamp: "2020-04-23T10:28:03Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1647309"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 238753c5-0d6b-400a-b16b-23cf4818c120
