---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-care-deployment
  labels:
    app: customercare
  namespace: phoenix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customercare
  template:
    metadata:
      labels:
        app: customercare
    spec:
      containers:
      - name: customer-care-pho
        image: 555256523315.dkr.ecr.us-east-1.amazonaws.com/phoenix:latest
        imagePullPolicy: Always
        # env:
        #   - name: ConnectionStrings__DefaultConnection
        #     valueFrom:
        #       secretKeyRef:
        #         name: conn-str
        #         key: conn-str-behemoth
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 5000

# REMOVE NGINX LB
# ADD LOAD BALANCER
# MAP PORT
